"""Render the derived status view.

The rendered document is a BUILD ARTIFACT, not a source of truth, and it carries a header
with a content hash so a hand edit is detectable. That is the whole point of moving this out
of markdown: the document can be regenerated rather than maintained, and therefore cannot
accumulate drift.
"""
from __future__ import annotations

import datetime as dt
import hashlib

from . import models

GENERATED_BANNER = ("<!-- GENERATED by monitor-mcp. Do not edit by hand. "
                    "Regenerate with render_status(). -->")


def _body_sha(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]


def render_status(payload: dict, *, generated_at: dt.datetime | None = None) -> str:
    """payload is the dict returned by store.status()."""
    now = generated_at or dt.datetime.now(dt.timezone(dt.timedelta(hours=8)))
    rows = payload.get("rows", [])

    body = [
        "# Signal registry status",
        "",
        f"- generated: {now.isoformat(timespec='seconds')}",
        f"- database: `{payload.get('db_path', '?')}`",
        f"- schema version: {payload.get('schema_version', '?')}",
        f"- signals: {payload.get('signals', 0)} (retired {payload.get('retired', 0)})",
        f"- entities: {payload.get('entities', 0)}",
        f"- readings recorded: {payload.get('readings', 0)}",
        f"- never read: {payload.get('never_read', 0)}",
        "",
        "## State summary",
        "",
        "| state | rows |",
        "|---|---|",
    ]
    for state in models.DERIVED_STATES:
        n = payload.get("by_state", {}).get(state, 0)
        if n:
            body.append(f"| {state} | {n} |")

    body += [
        "",
        "## Rows",
        "",
        "| legacy | slug | kind | cadence | state | last slot | value | overdue (d) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    rank = {s: i for i, s in enumerate(models.DERIVED_STATES)}
    for r in sorted(rows, key=lambda x: (rank.get(x["state"], 9), -(x["overdue_days"] or 0.0))):
        body.append(
            f"| {r['legacy_row'] if r['legacy_row'] is not None else '-'} "
            f"| {r['slug']} | {r['kind']} | {r['cadence']} | {r['state']} "
            f"| {r['last_slot'] or '-'} "
            f"| {r['value_num'] if r['value_num'] is not None else '-'} "
            f"| {r['overdue_days'] if r['overdue_days'] is not None else '-'} |"
        )

    body += ["", "## Derived states", "", "| state | meaning |", "|---|---|"]
    for state in models.DERIVED_STATES:
        body.append(f"| {state} | {models.STATE_MEANING[state]} |")
    body.append("")

    text = "\n".join(body)
    return f"{GENERATED_BANNER}\n<!-- body-sha256: {_body_sha(text)} -->\n\n{text}"


def _split(rendered: str) -> tuple[str | None, str | None]:
    """Return (stored_sha, body) from a rendered document."""
    lines = rendered.split("\n")
    if len(lines) >= 3 and lines[0].startswith("<!-- GENERATED") and "body-sha256:" in lines[1]:
        stored = lines[1].split("body-sha256:")[1].strip().rstrip("-->").strip()
        return stored, "\n".join(lines[3:])
    return None, None


def verify(rendered: str) -> bool:
    """True when the rendered document is unmodified since it was generated."""
    stored, body = _split(rendered)
    if stored is None or body is None:
        return False
    return stored == _body_sha(body)
